services:
  backend:
    image: ghcr.io/a-y-a-n-das/course-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    networks:
      - coursehive

  frontend:
    image: ghcr.io/a-y-a-n-das/course-frontend:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - coursehive

networks:
  coursehive:
    driver: bridge
